### ISSUE TITLE
Hi everyone!

### ISSUE THREAD

**Issue by vweevers** [airtap/airtap#1]
Hi @mcollina @yoshuawuyts @feross,

Because [zuul](https://github.com/defunctzombie/zuul) is unmaintained, @mcollina suggested we spin up a new project (https://github.com/nodejs/readable-stream/pull/320#issuecomment-364178156). To get us started I forked zuul to this new org (for isolated Travis and Sauce Labs accounts). I also considered [smokestack](https://github.com/hughsk/smokestack) as a starting point but it is not feature-complete when it comes to testing multiple browsers on Sauce Labs.

Possible consumers include [readable-stream](https://github.com/nodejs/readable-stream), [memdown](https://github.com/Level/memdown) and  [abstract-leveldown](https://github.com/Level/abstract-leveldown/issues/123).

The main goal, besides basic maintenance like updating node versions, is to reduce the scope. Build something that is easy to maintain. I think we will mostly *remove* features, not add new ones like BrowserStack support. At the very least, let's remove localtunnel in favor of Sauce Connect (will need https://github.com/defunctzombie/zuul/pull/323) which has proven to be more reliable.

Maybe we can also remove phantomjs, electron and frameworks other than tap(e)? I'll open issues to discuss this.

@mcollina I did not know who you meant by "add all of us", so can you please add
whoever you think is willing to help out? Thanks!

@ralphtheninja @juliangruber want to join? :)

**Comment by ralphtheninja** [comment]
> @ralphtheninja @juliangruber want to join? :)

@vweevers Count me in!

**Comment by vweevers** [comment]
@juliangruber Sauce Labs is a hard requirement.

**Comment by juliangruber** [comment]
what is this using sauce labs for?

**Comment by vweevers** [comment]
`readable-stream` runs tests on IE 9+ and Edge, Opera 11+, Chrome, Firefox and Safari 5+. `memdown` has a similar matrix (but less versions) and also includes ipad, iphone and android (mostly for PouchDB).

**Comment by juliangruber** [comment]
gotcha, thanks! I was using testling with tape for cross browser testing, but unfortunately testling itself isn't working any more

**Comment by mcollina** [comment]
Count me in as well. This has been a huge pain for readable-stream.

**Comment by juliangruber** [comment]
Has anyone looked at this? Just discovered it today https://github.com/hughsk/smokestack by @hughsk

**Comment by vweevers** [comment]
@juliangruber yup as I wrote in the OP:

>  I also considered smokestack as a starting point but it is not feature-complete when it comes to testing multiple browsers on Sauce Labs.

**Comment by juliangruber** [comment]
sorry bout that 🙈

**Comment by feross** [comment]
Count me in! I find `zuul` a huge pain when testing the various WebTorrent libraries and also [`buffer`](https://github.com/feross/buffer) for browserify. I think that @jhiesey also has an interest in this project for testing [`stream-http`](https://github.com/jhiesey/stream-http) for browserify. He's said that `zuul` is currently basically unusable for him too. Can you add @jhiesey?

**Comment by ralphtheninja** [comment]
@feross Added.

**Comment by vweevers** [comment]
Hi all, our first release is out! If you want to take the leap, see [`UPGRADING.md`](https://github.com/airtap/airtap/blob/master/UPGRADING.md) for how to migrate from zuul. 

@ralphtheninja and I will work on getting it into `memdown`.

See `Todo` in our [project board](https://github.com/orgs/airtap/projects/1) for what will be released next.

With that, I'm closing this issue. 🎈
