### ISSUE TITLE
Drop support for Node 4.x

### ISSUE THREAD

**Issue by yeskunall** [airtap/airtap#102]
Node 4.x is currently in maintenance, but will soon reach EOL, 2018-04-30 to be precise. Since we are making heavy changes and refactoring the library quite a bit, might I suggest, during that process, we also have a discussion on whether we should drop support for Node 4.x as well?

I want to make this more of a discussion, rather than a statement, so please feel free to chime in and let me know what your thoughts are on this.

<hr />

More on Node LTS [here](https://github.com/nodejs/Release#release-schedule).

**Comment by mcollina** [comment]
I’m +1 with removing Node 4 right now.
Il giorno dom 25 feb 2018 alle 05:06 Kunall Banerjee <
notifications@github.com> ha scritto:

**Comment by ralphtheninja** [comment]
I'm also +1 on dropping right now.

**Comment by ralphtheninja** [comment]
> What's the benefit of dropping 4 before EOL?

The only benefit I can see right now is speeding up tests.

**Comment by vweevers** [comment]
OK, I have no problems with dropping 4. As long as we do follow the LTS schedule in the future.

**Comment by ralphtheninja** [comment]
We can also bump `dependency-check` to the latest.
