### ISSUE TITLE
Make this an OPEN Open Source Project

### ISSUE THREAD

**Issue by vweevers** [airtap/airtap#12]
By that I mean http://openopensource.org/

**Comment by mcollina** [comment]
Go ahead 👍

**Comment by ralphtheninja** [comment]
This should be high priority. It signals to the community that the project is active and that we encourage contributions.

**Comment by ralphtheninja** [comment]
Point 1 can be a bit silly though, since you should be allowed to rebase and squash branches during a PR.

**Comment by vweevers** [comment]
> Point 1 can be a bit silly though, since you should be allowed to rebase and squash branches during a PR.

Yea. We can copy the default `contributing.md` and tweak afterwards.
