### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by vweevers** [airtap/airtap#13]
Also: remove `.npmrc`.

**Comment by ralphtheninja** [comment]
Oh wow, that's a lot of dependencies. Maybe start by updating all to latest and then gradually remove?

**Comment by vweevers** [comment]
I think, first remove the features that we don't need anymore (#9, #7, ..), which will hopefully get rid of some dependencies, and only then start upgrading. Our test suite has low coverage (from what I saw) so we should be careful to upgrade too much at once.

**Comment by ralphtheninja** [comment]
@vweevers I'd really like to start using [`dependency-check`](https://github.com/maxogden/dependency-check) but it requires node 6 to use the latest. Maybe we can pin `dependency-check` at `2.10.0` and then upgrade that once node 4 is dead.

**Comment by vweevers** [comment]
Great idea!

**Comment by ralphtheninja** [comment]
I'll start there. It should help out a lot when removing dependencies.

**Comment by ralphtheninja** [comment]
I'll update all dependencies now. Just noticed `lodash` is being used, which can probably be split into specific `lodash-*` modules.

**Comment by mcollina** [comment]
I would actually see if we can remove it altogether.

**Comment by ralphtheninja** [comment]
> I would actually see if we can remove it altogether.

Even better :smile:

**Comment by ralphtheninja** [comment]
Either way, I'll start by updating everything and we can reduce from there.

**Comment by ralphtheninja** [comment]
@vweevers Perhaps now is a good time to go through the dependencies? Since the tests pass, I could push to a separate branch with single commits per dependency update.

**Comment by vweevers** [comment]
Yup, I had the same idea, so I placed this issue at the top of Todo. Do your thang!

**Comment by ralphtheninja** [comment]
Just going to make some quick notes here as I progress. I noticed that bumping `browserify` to latest version messes up tests, also `express` has deprecated `app.router`. I'm guessing I'll run into more problems as I go, so will just make a list here for now on modules that needs special care

- [ ] `browserify` 13.0.0 => ~16.1.0 https://travis-ci.org/airtap/airtap/jobs/343022028
- [ ] `express` 3.4.8 => ~4.16.2 https://travis-ci.org/airtap/airtap/jobs/343168012 (also seems to require a newer version of `express-state`)

**Comment by goto-bus-stop** [comment]
as for the browserify failure, buffer@5.1 requires `ArrayBuffer.isView` and thus dropped support for IE 10 and Node 0.10. (Although i'm not sure if IE 10 was officially supported anyway) That may have something to do with it?

**Comment by ralphtheninja** [comment]
@vweevers Testing things by pushing up and waiting for sauce labs to run the code is a huge pain. Is there any way I can test e.g. the `tape` code locally so I can find out what the problems is with `tap-parser` (and `tap-finished`)? Nothing happens and I get no output.

**Comment by vweevers** [comment]
Maybe try:

```
mocha --ui qunit --timeout 0 --bail -- test/integration/tape-phantom.js
```

**Comment by vweevers** [comment]
You could also try the `example` directory, run it with `airtap --local 8080 test.js`.

**Comment by vweevers** [comment]
If those two do work locally, you could try restarting the Travis job to rule out a random failure and/or looking at the Sauce Labs dashboard (it sometimes shows errors that are not propagated back to airtap).

**Comment by ralphtheninja** [comment]
> as for the browserify failure, buffer@5.1 requires ArrayBuffer.isView and thus dropped support for IE 10 and Node 0.10. (Although i'm not sure if IE 10 was officially supported anyway) That may have something to do with it?

@vweevers So, I guess updating `browsers` is needed to only test for 11 (since 9 and 10 are old)

**Comment by vweevers** [comment]
> So, I guess updating browsers is needed to only test for 11 (since 9 and 10 are old)

`readable-stream` tests against IE 9+ though. cc @mcollina

**Comment by vweevers** [comment]
@ralphtheninja I can also send you SL credentials if you want and share a snippet to easily run Sauce Connect. Then you can at least bypass Travis, and start the test suite from your machine. Just have to make sure you don't run Travis builds at the same time, or you'll run into the concurrency limit.

**Comment by ralphtheninja** [comment]
> readable-stream tests against IE 9+ though. cc @mcollina

So then we shouldn't use the latest `browserify`

**Comment by ralphtheninja** [comment]
> @ralphtheninja I can also send you SL credentials if you want and share a snippet to easily run Sauce Connect. Then you can at least bypass Travis, and start the test suite from your machine. Just have to make sure you don't run Travis builds at the same time, or you'll run into the concurrency limit.

Too much in my head right now. Maybe later :)

**Comment by goto-bus-stop** [comment]
browserify does aim to support lots of old stuff, its tests are also failing because of ArrayBuffer.isView, so I might pin buffer to 5.0.x there.

**Comment by ralphtheninja** [comment]
> browserify does aim to support lots of old stuff, its tests are also failing because of ArrayBuffer.isView, so I might pin buffer to 5.0.x there. but yeah in the mean time airtap will have to use an older version to support IE9. the only pain point in that case i think is that browserify only supports the latest ES syntax since 15+, IIRC.

@goto-bus-stop Know which major version I should pick? Using 13 now.

**Comment by goto-bus-stop** [comment]
13 is the last version with buffer@4, so should stay on that.

actually buffer@5.x have all dropped IE9 support so it won't work in newer browserify even if i pin it to 5.0.

(It might be worth upgrading anyway in the future and use a typed array polyfill in projects that need to work in IE < 10.)

**Comment by ralphtheninja** [comment]
@vweevers Would you mind if I submitted a PR of the work I have done this far?

Basically we now have:

* `browserify` it's stuck at 13 for now since we can't mess up support for IE9+ just yet
* `dependency-check` itself (we bump this once node 4 has reached EOL)
* `mocha` want to fix this in a separate PR
* `tap-parser` want to fix this in a separate PR

![screenshot from 2018-02-19 23-31-54](https://user-images.githubusercontent.com/308049/36399674-3a07f5a6-15cd-11e8-8911-233dc440a096.png)

**Comment by vweevers** [comment]
@ralphtheninja I skimmed through the dependencies and opened a few issues for things we can remove: #48, #49, #50, #51, #52.

**Comment by ralphtheninja** [comment]
Closing this, since I'll remove `mocha` shortly.
