### ISSUE TITLE
Add test-local script

### ISSUE THREAD

**Issue by vweevers** [airtap/airtap#140]
From https://github.com/airtap/airtap/pull/134#discussion_r175268706:

> @ralphtheninja: Maybe we should have a test-local target which runs everything but the sauce tests.

**Comment by ralphtheninja** [comment]
How about defaulting `npm test` to running the local tests only and instead have `.travis.yml` do e.g. `npm run test-all`? It's handy when testing locally to have it only run local tests by default.

**Comment by vweevers** [comment]
It can also be handy to initiate Sauce Labs tests from your local machine.

**Comment by ralphtheninja** [comment]
> It can also be handy to initiate Sauce Labs tests from your local machine.

We can have a targer for that for sure. I'll make a PR and we can discuss further from there.
