### ISSUE TITLE
Remove dead tags option

### ISSUE THREAD

**Issue by vweevers** [airtap/airtap#147]
Defined here:

https://github.com/airtap/airtap/blob/d636665b843504ff1f35942d6d8ff22d6d41fe7f/lib/sauce-browser.js#L56-L59

Theoretically used [to tag Sauce Labs builds to identify them](https://wiki.saucelabs.com/display/DOCS/Test+Configuration+Options#TestConfigurationOptions-Tagging).

But `tags` isn't passed from either CLI or YAML options to `SauceBrowser`:

https://github.com/airtap/airtap/blob/d636665b843504ff1f35942d6d8ff22d6d41fe7f/lib/airtap.js#L49-L59

We can either remove this feature, or complete it.

**Comment by ralphtheninja** [comment]
I vote for removing.

**Comment by vweevers** [comment]
Me too.
