### ISSUE TITLE
Invalid browser name should throw an error

### ISSUE THREAD

**Issue by feross** [airtap/airtap#154]
When the user-specified browser name does not match any in Sauce Labs, we should throw an error instead of silently skipping that browser (which is what we do now).

I've been bitten by this a few times already.

**Comment by ralphtheninja** [comment]
@feross Could you provide a real example of where this went wrong? Did you type something wrong in e.g. `.airtap.yml`?

**Comment by vweevers** [comment]
It happened with MS Edge (#155)

**Comment by ralphtheninja** [comment]
Ok, so that fixes a problem with lower case. Should we still throw if there's no match at all? E.g. here https://github.com/lpinca/sauce-browsers/blob/663dfed959dfb9825fb52495a9ff6bf063357ada/index.js#L93

**Comment by ralphtheninja** [comment]
https://github.com/lpinca/sauce-browsers/commit/bf97a19d65025fd974e79b55ad856c58b293d542
