### ISSUE TITLE
rewrite README

### ISSUE THREAD

**Issue by ralphtheninja** [airtap/airtap#16]
- [x] Badges
- [x] Remove `Frameworks` section
- [x] Add short description
- [x] Replace images with local ones
- [x] Remove `Credits` section
- [x] Add copyright notice (without year) and Zuul credits to `License` section
- [x] And most importantly: #10

**Comment by vweevers** [comment]
Also:

- Replace images with local ones
- Remove `Credits` section
- Add copyright notice (without year) and Zuul credits to `License` section
- And most importantly: https://github.com/airtap/airtap/issues/10
