### ISSUE TITLE
Dedup browsers based on OS and device

### ISSUE THREAD

**Issue by ralphtheninja** [airtap/airtap#168]
See https://github.com/airtap/browsers/issues/3#issuecomment-392005173

**Comment by ralphtheninja** [comment]
These property translations are painful to me. In other words we should dedupe on `.os` and `.api_name` properties in the _original_ data we get from `sauce-browsers`.

They translate into:

* `.os` -> `.platform`
* `.api_name` -> `.browser`

But isn't the the final `.version` property important as well? So maybe it's the data to `zuul.browser()` that should be unique:

https://github.com/airtap/airtap/blob/c760dac878943dbf66745097edf254ac67eda49c/bin/airtap.js#L153-L157

**Comment by vweevers** [comment]
I think, if you want to avoid touching the translations (but go for it if you feel up to it), it's easiest to add a check here, at the last possible moment:

https://github.com/airtap/airtap/blob/c760dac878943dbf66745097edf254ac67eda49c/lib/airtap.js#L48-L58

I.e.: do we already have browser with that `name`, `version` and `platform`? Then don't `push()` another.

**Comment by ralphtheninja** [comment]
> I.e.: do we already have browser with that name, version and platform? Then don't push() another.

Aye, exactly. I just wanted to make sure we're on the same page. That's probably the easiest way indeed. If I find some stuff that can be cleaned safely, they will be cleaned.
