### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by feross** [airtap/airtap#170]
Do we think this is stable enough at this point that we can switch to normal semver version numbers? It's really useful to know major = breaking, minor = new feature, patch = bugfix.

Our current version numbers < 1.0.0 is much less clear.

If we're not ready for 1.0.0, what are the changes we want to make first?

**Comment by vweevers** [comment]
I attached a bunch of issues to v1 (open for discussion): https://github.com/airtap/airtap/milestone/1

**Comment by ralphtheninja** [comment]
Sounds good to me and the milestone doesn't look that massive either. Once we feel we're done, I'd like to release an `rc` so we can test it out on a few projects (`memdown`) before releasing `1.0.0`.

**Comment by feross** [comment]
Btw, I have a selfish motivation for wanting to get on semver. Every time we do an airtap release, I get this in my inbox 😭

<img width="825" alt="screen shot 2018-05-25 at 7 16 11 am" src="https://user-images.githubusercontent.com/121766/40549157-9a1fc0fa-5feb-11e8-9508-38a70d193241.png">

`zuul` was causing so many problems that I still prefer this!

**Comment by vweevers** [comment]
@feross: woa 😁. Slightly off topic, but I'm curious: do you have Sauce Labs accounts per project, or just 1 account?

**Comment by feross** [comment]
@vweevers One account per project. I created them before Sauce Labs made you email them to get permission first, so it was easy to make many accounts. (In hindsight, a lot of these packages don't need browser testing since they don't interact with the DOM. But when I originally wrote most of them, there were more bugs and compat issues in browsers)

**Comment by vweevers** [comment]
I released 1.0.0 and will release 2.0.0 in a few minutes, per the plan in https://github.com/airtap/airtap/issues/171#issuecomment-449635555. I renamed [the milestone](https://github.com/airtap/airtap/milestone/1) (previously meant for v1) to `next`.
