### ISSUE TITLE
Remove code coverage?

### ISSUE THREAD

**Issue by ralphtheninja** [airtap/airtap#176]
The main use case now is to run `tape`/`tap` to test functionality in different browsers. Code coverage isn't really related to that at all (my opinion).

I'm suggesting we remove code coverage completely. This would reduce a lot of complexity. We would also get rid of [`istanbul-middleware`](https://github.com/gotwarlost/istanbul-middleware#readme) which hasn't been updated since 2015.

Also see https://github.com/airtap/airtap/issues/156#issuecomment-394162657

**Comment by vweevers** [comment]
We would need a replacement for `istanbul-middleware` later (for #162), as it's hard to inject the necessary instrumentation from outside airtap.

**Comment by vweevers** [comment]
> Code coverage isn't really related to that at all (my opinion).

I don't agree. Different browsers will have different coverage, and it's important to measure.

**Comment by vweevers** [comment]
Also, some modules (`level-js`) are browser-only, so that's the only place coverage *can* be collected. A browserify transform could do that, but it'd still need airtap to move the reports from browser to node.

I'm fine with removing `istanbul-middleware` to solve the vulnerability, it's not working anyway, but not with permanently dropping coverage as a feature.

**Comment by ralphtheninja** [comment]
> We would need a replacement for istanbul-middleware later (for #162), as it's hard to inject the necessary instrumentation from outside airtap.

That's actually my main concern here, old dependencies that aren't maintained. If you think coverage is important and relevant I'm not against it at all.

**Comment by ralphtheninja** [comment]
@vweevers I'm not sure how to tackle removing `istanbul-middleware`. Would it be enough to comment out the following for now (with some comments)?

https://github.com/airtap/airtap/blob/82deda23442e1022a4e9b2c64ff3f2037e52c956/lib/control-app.js#L80-L83

**Comment by vweevers** [comment]
Also need to prevent the client from trying to send to that endpoint:

https://github.com/airtap/airtap/blob/82deda23442e1022a4e9b2c64ff3f2037e52c956/client/reporter.js#L259-L268
