### ISSUE TITLE
Migrate tests from mocha to tape

### ISSUE THREAD

**Issue by ralphtheninja** [airtap/airtap#19]

**Comment by ralphtheninja** [comment]
@vweevers I guess you want to make the tests run first using `mocha` before we start using `tape`?

**Comment by vweevers** [comment]
Yes. Once our tests pass, we could do #14 (as well as the small stuff in To Do), cut a 0.0.1 release, which memdown can start using right away, after which we make bigger changes like migrating to tape.

**Comment by ralphtheninja** [comment]
> Yes. Once our tests pass, we could do #14 (as well as the small stuff in To Do), cut a 0.0.1 release, which memdown can start using right away, after which we can start with bigger changes like migrating to tape.

I like the approach of getting it to work and putting it in use as fast as possible before doing any major changes!

**Comment by ralphtheninja** [comment]
Two servers down :smile: 

Now I need to figure out how to stop `watchify`.
