### ISSUE TITLE
Release 0.0.9

### ISSUE THREAD

**Issue by vweevers** [airtap/airtap#195]

**Comment by vweevers** [comment]
@ralphtheninja does the coverage change warrant an entry in `UPGRADING.md`?

**Comment by ralphtheninja** [comment]
I think so, since we disabled it before.

**Comment by ralphtheninja** [comment]
@vweevers I can prepare 0.0.9 if you like.

**Comment by vweevers** [comment]
Sure, if not, I'll do it somewhere this week.
