### ISSUE TITLE
Split mixed-type flags like --local

### ISSUE THREAD

**Issue by vweevers** [airtap/airtap#198]
Currently `--local` can be a boolean or a number, e.g. `--local 3000`. This gets quirky if you do `--local test.js`. If `--local` is the last flag, you must do `--local -- test.js`.

IMO the port should be a separate option.

https://github.com/airtap/airtap/blob/aa10b3b62d469f0549ee42c03b58376461c658eb/bin/airtap.js#L27

Same for `--sauce-connect`. Which BTW, we could remove altogether? Because Sauce Connect is the only supported tunnel.

https://github.com/airtap/airtap/blob/aa10b3b62d469f0549ee42c03b58376461c658eb/bin/airtap.js#L29

/cc @mcollina because you got bitten by this in https://github.com/nodejs/readable-stream/pull/340

**Comment by mcollina** [comment]
+1 on having `--port` option.

**Comment by mcollina** [comment]
I also think that having  `-- test.js` is better overall.
