### ISSUE TITLE
Move wiki to a doc folder

### ISSUE THREAD

**Issue by mcollina** [airtap/airtap#20]
Having a doc folder enables better versioning and tracking of changes.

**Comment by vweevers** [comment]
Depends on how much of it we'll actually need. Some of the wiki instructions can be found elsewhere (like Travis setup, npm basics), some of it can be shortened, some will be irrelevant. So maybe it can all go in the readme.

**Comment by vweevers** [comment]
But putting it in a doc folder is a good start in any case :)

**Comment by ralphtheninja** [comment]
> Depends on how much of it we'll actually need. Some of the wiki instructions can be found elsewhere (like Travis setup, npm basics), some of it can be shortened, some will be irrelevant. So maybe it can all go in the readme.

We could have a smaller "get started"-section in the readme to help people get it up and running and with the bare essentials and put more details in e.g. `doc/README.md`.
