### ISSUE TITLE
Rewrite capabilities tests as unit test

### ISSUE THREAD

**Issue by vweevers** [airtap/airtap#24]
It only asserts that the `capabilities` option can be set:

https://github.com/airtap/airtap/blob/62c9b61c2be94d7135e09f4d4012000a8ee5da8e/test/integration/capabilities.js#L26-L28

So it shouldn't (need to) start a browser.

**Comment by ralphtheninja** [comment]
Nit: It shouldn't need to pass in authentication details either, which means `auth.js` can be pulled into `tape-sauce.js`.
