### ISSUE TITLE
Give credit to Sauce Labs

### ISSUE THREAD

**Issue by vweevers** [airtap/airtap#26]
A request from Sauce Labs:

> We would also like to request that you give credit to Sauce Labs, via either a text link and/or logo and link on your repo and project website, should there be a pubic-facing site; I've attached logo artwork and a MD file with text. If you'd like to write a blog post about your project we're happy to publish it on the Sauce Labs website, and shoutouts on Twitter are always appreciated! 

Files (SVG, PNG and MD files): [sauce labs assets.zip](https://github.com/airtap/airtap/files/1732165/sauce.labs.assets.zip)

**Comment by mcollina** [comment]
definitely 👍 !

**Comment by ralphtheninja** [comment]
Of course! A blog post would be cool.
