### ISSUE TITLE
Update screenshot

### ISSUE THREAD

**Issue by vweevers** [airtap/airtap#27]
A request from Sauce Labs:

> If possible, it would be great if you could also update this screenshot to reflect our current branding:
> ![image](https://user-images.githubusercontent.com/3055345/36320345-33bc11d4-1346-11e8-9167-569cb0dcfac7.png)

**Comment by vweevers** [comment]
How about we replace this with a live status matrix, like the one in [memdown#browser-support](https://github.com/Level/memdown#browser-support)? And add a note saying "airtap itself is tested on Sauce Labs".

**Comment by ralphtheninja** [comment]
Good idea! Eat your own dogfood :)

**Comment by vweevers** [comment]
Or maybe not, because our test suite also tests failures. Our build is passing, but it doesn't look like it 😄 

![image](https://user-images.githubusercontent.com/3055345/36350441-03b4bc36-1498-11e8-8a49-0360566e7faf.png)

**Comment by vweevers** [comment]
Once `memdown` is using `airtap`, we can replace the browser matrix with a screenshot of one of memdown's build jobs.

**Comment by ralphtheninja** [comment]
@vweevers Once `level.js` is incorporated into `level` we could replace `memdown` with `level`.
