### ISSUE TITLE
Option to disable polyfills

### ISSUE THREAD

**Issue by kibertoad** [airtap/airtap#301]
In https://github.com/fastify/secure-json-parse/pull/21 we've observed that `airtap` does not allow to reproduce actual browser behaviour due to the included polyfills via Browserify. This significantly reduces the benefits of using `airtap`.
Would it be possible to make polyfilling optional?

**Comment by denis-sokolov** [comment]
It might be possible to configure Browserify by providing [an empty `--insert-global-vars` option](https://github.com/browserify/browserify#usage). I have not tried it, but this may be a starting point for further research.

**Comment by vweevers** [comment]
Yes, this should be possible through browserify options. Will check that out. If it's too cumbersome or verbose, we can add an airtap option as a shortcut.

**Comment by kibertoad** [comment]
Thank you!

**Comment by vweevers** [comment]
Add the following to `.airtap.yml`:

```yaml
browserify:
  - options:
      bare: true
```

From [`browserify` docs](https://github.com/browserify/browserify#browserifyfiles--opts):

> `opts.bare` creates a bundle that does not include Node builtins, and does not replace global Node variables except for `__dirname` and `__filename`

Does that suffice?

**Comment by vweevers** [comment]
If not, can reopen. Let us know 🌞
