### ISSUE TITLE
Hangs indefinitely if no .airtap.yml (without a warning)

### ISSUE THREAD

**Issue by jzombie** [airtap/airtap#313]
Was just setting up a new project and couldn't figure out why the airtap program was just hung.   Went through a lot of trial and error before I realized that I was missing the .airtap.yml file.

Would be nice if it gave some sort of indication, warning, or error if it is missing the file.

**Comment by vweevers** [comment]
If there's no `.airtap.yml` then airtap should open the default browser, perhaps this is failing. Try adding the `--silly` flag (enables all debug output) to see what's going on.

**Comment by jzombie** [comment]
So, the issue was that I was using a remote SSH session to initiate the tests with (wasn't even thinking about that).

Works as designed when running locally.

Closing the issue.
