### ISSUE TITLE
re-implement `serve-static`

### ISSUE THREAD

**Issue by ThaUnknown** [airtap/airtap#327]
`serve-static` would be needed for testing and registering service workers as they need to come from the same origin and scope, using a support server won't work, additionally service workers can't be registered using blobs, it has to be static files.
Running a script to register a worker before running airtap won't work as ports change too.

**Comment by vweevers** [comment]
Airtap runs a proxy server, that forwards any URL that does not start with `/airtap` to the support server (if any). So you can ensure the origin matches by using the port of the proxy server.

**Comment by ThaUnknown** [comment]
i see
