### ISSUE TITLE
Running tests locally fails

### ISSUE THREAD

**Issue by ralphtheninja** [airtap/airtap#39]
![screenshot from 2018-02-18 15-40-53](https://user-images.githubusercontent.com/308049/36353084-297b4a6e-14c2-11e8-9bb6-06b1482e8701.png)

**Comment by vweevers** [comment]
Yes, you need 1) sauce labs credentials and 2) sauce connect.

**Comment by ralphtheninja** [comment]
Aye, I was just thinking a `test-browser-local` could be used here.

**Comment by vweevers** [comment]
Just opened an issue for that 😄
