### ISSUE TITLE
Configure CI and get tests passing

### ISSUE THREAD

**Issue by vweevers** [airtap/airtap#4]
- [x] Create GH machine user
- [x] Create Sauce Labs account
- [x] Send email to Sauce Labs [to make it an open source account](https://saucelabs.com/open-source) (I ran out of minutes)
- [x] ~~Exit early in `test/auth.js` if credentials are missing~~ later
- [x] Use `cross-env` in npm test
- [x] Change tunnel config in `mocha-qunit-sauce.js` to `{ type: 'ngrok', bind_tls: true }` (I'll explain)
- [x] Fork `browzers` to `airtap/browsers`
  - [x] Rename: airtap/browsers#1
  - [x] Update browsers: airtap/browsers#2
- [x] Use `airtap-browsers`
- [x] Activate Travis
- [x] ~~Put Sauce Labs credentials in `.travis.yml`~~ Add through Travis settings

**Comment by ralphtheninja** [comment]
@vweevers Can you fill me in about the Sauce Labs credentials in `.travis.yml`. Why are they needed? Because we want to run the _airtap_ tests inside a browser as well?

**Comment by vweevers** [comment]
> Because we want to run the airtap tests inside a browser as well?

Yup. Without credentials the tests don't amount to much (there's a lack of unit tests IMO, as opposed to integration tests).

**Comment by ralphtheninja** [comment]
I'd like to replace `mocha` with `tape` in that case.

**Comment by vweevers** [comment]
Yes yes and yup to the yes!

**Comment by vweevers** [comment]
Got a response from Sauce Labs, we're good. They made some requests (like updating an old screenshot to reflect their branding) which I'll open issues for.

I'll continue with this in ~9 hours, should be able to get it going real fast.

**Comment by vweevers** [comment]
> should be able to get it going real fast.

Ha. Well, the tests pass locally for me (including the Sauce Labs tests), but from Travis:

- ngrok was complaining about too many tunnels, so I registered an account with them and fixed a bug in airtap so that tunnels are properly closed
- Then ngrok complained about too many connections, so I upgraded to a paid account
- Then the builds just halted during tests, with no further output in Travis, or any signal from Sauce Labs or the ngrok dashboard
- So I tried Sauce Connect instead, but browsers fail to connect to zuul's server.

I sincerely hope I made a mistake somewhere. See the [fix-tests](https://github.com/airtap/airtap/compare/master...fix-tests) branch. I'll try again tomorrow and break it down into small PRs for review.

**Comment by vweevers** [comment]
We might want to give `smokestack` a spin on Sauce Labs, to see if Travis or SL is the problem (but I don't think so).

**Comment by mcollina** [comment]
Should we ping the folks at SauceLabs?

**Comment by vweevers** [comment]
Found my mistake. I forgot the `sauce_connect: true` option 🙈

**Comment by vweevers** [comment]
Yes, first green build: https://travis-ci.org/airtap/airtap/builds/342064403. This further cements my belief that Sauce Connect is the way to go.
