### ISSUE TITLE
Inheritance should use inherits module or util.inherits, no __proto__ stuff

### ISSUE THREAD

**Issue by ralphtheninja** [airtap/airtap#42]

**Comment by yeskunall** [comment]
After taking a quick look, looks like `lib/airtap.js` (formerly `lib/zuul.js`) uses `__proto__` stuff. Can't we refactor it to use ES6 classes instead? Just wondering. 😅

**Comment by ralphtheninja** [comment]
We definitely could do that, but I personally don't see the advantage of using es6 classes. Maybe I'm just old :smile:

**Comment by yeskunall** [comment]
I think I mostly agree with you on this. For me, I only ever use ES6 classes to refactor old code (like in this case) because it keeps more or less the same structure, but vastly improves readability. 😅

**Comment by feross** [comment]
FWIW, I've come around and now I think ES6 Classes are great :) `inherits` is also fine!

Will this affect browser compat? I think we don't want to lose old IE support yet, right?

**Comment by ralphtheninja** [comment]
![screenshot from 2018-02-23 02-37-50](https://user-images.githubusercontent.com/308049/36573696-988fb18c-1842-11e8-8641-68142b92e6c0.png)

It's all server side so we should be good!

**Comment by yeskunall** [comment]
I'll start working on it. Or should I wait till #75 gets merged? 😁

**Comment by ralphtheninja** [comment]
@yeskunall I'm doing it right now as part of finishing `standard`

**Comment by ralphtheninja** [comment]
Should we use `inherits` or `util.inherits`? Does it matter?

**Comment by vweevers** [comment]
It's only server-side, right? So `util.inherits` is fine.

**Comment by lpinca** [comment]
You can also avoid using `util.inherits` and use `Object.setPrototypeOf()` instead which is what util.inherits uses under the hood.

```js
function MountainBike() {
  Bicycle.call(this);
}

Object.setPrototypeOf(MountainBike.prototype, Bicycle.prototype);
```
