### ISSUE TITLE
replace char-split with split2

### ISSUE THREAD

**Issue by ralphtheninja** [airtap/airtap#43]
Mainly because streams vs streams2 and `char-split` haven't been touched in five years.

**Comment by jeffreyshen19** [comment]
Just created a PR at https://github.com/airtap/airtap/pull/80

**Comment by ralphtheninja** [comment]
@jeffreyshen19 Tip: When you make a PR you can type "Closes #NUMBER" in the PR and once it's merged the corresponding issue will automatically be closed.
