### ISSUE TITLE
consider extracting lib/get-saucelabs-browsers.js into separate module, e.g. saucelabs-browsers

### ISSUE THREAD

**Issue by ralphtheninja** [airtap/airtap#44]
Maybe also use something higher level to abstract away the buffering and JSON.parse code

**Comment by lpinca** [comment]
I wrote https://github.com/lpinca/sauce-browsers for [eventemitter3](https://github.com/primus/eventemitter3) and [url-parse](https://github.com/unshiftio/url-parse). It is almost a drop-in replacement.
