### ISSUE TITLE
Use rc for .airtaprc

### ISSUE THREAD

**Issue by vweevers** [airtap/airtap#51]

**Comment by ralphtheninja** [comment]
I thought about this as well. But it would mean we would have different types of configurations, yaml for local and json/ini for global. But maybe it's not a big deal?

**Comment by vweevers** [comment]
> But it would mean we would have different types of configurations, yaml for local and json/ini for global. 

That's fine. I didn't expect the `.rc` file to be YAML. And it'll be documented.

**Comment by vweevers** [comment]
Closing; no interest.
