### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by ralphtheninja** [airtap/airtap#62]
I think there will be a lot of changes now in the beginning and I just want to communicate that I think it's important that we release often, until we feel the API has stabilized and we're ready for `1.0.0`.

We have `memdown` using it already and maybe we should try getting some other projects running it as well, so we can get feedback if there's any problems.

**Comment by ralphtheninja** [comment]
If you want publish access on npm, let me or @vweevers know.

**Comment by feross** [comment]
I'm currently using it on `simple-peer` and `magnet-uri`, as well.

**Comment by feross** [comment]
@ralphtheninja Happy to have npm publish access

**Comment by vweevers** [comment]
@feross added.

**Comment by feross** [comment]
@vweevers Nice.

Just added `airtap` to `buffer` and `webtorrent` as well. Now I have it on 4 repos. Will report any issues and breakage that I notice.

One thing I noticed is that `webtorrent` currently uses the `--electron` flag to also run tests in Electron. I removed that set of tests in order switch to `airtap`.

**Comment by vweevers** [comment]
> One thing I noticed is that webtorrent currently uses the --electron flag to also run tests in Electron. I removed that set of tests in order switch to airtap.

If you want to keep/restore Electron, let's discuss in #8.

**Comment by ralphtheninja** [comment]
@jhiesey Which projects are you using airtap for?

**Comment by jhiesey** [comment]
@ralphtheninja Currently just [stream-http](https://github.com/jhiesey/stream-http)

**Comment by feross** [comment]
We should add `stream-http` to the list of users in the readme!

**Comment by ralphtheninja** [comment]
> We should add stream-http to the list of users in the readme!

That's what I was getting at :smile:

**Comment by jhiesey** [comment]
Done. I meant to make a PR, but I forgot I hadn't forked the repo before cloning. Oops.
