### ISSUE TITLE
Commit package-lock.json?

### ISSUE THREAD

**Issue by ralphtheninja** [airtap/airtap#63]
[![](https://api.gh-polls.com/poll/01C6TY54JCCGEPKPCA154TVJ85/Yes)](https://api.gh-polls.com/poll/01C6TY54JCCGEPKPCA154TVJ85/Yes/vote)
[![](https://api.gh-polls.com/poll/01C6TY54JCCGEPKPCA154TVJ85/No)](https://api.gh-polls.com/poll/01C6TY54JCCGEPKPCA154TVJ85/No/vote)

**Comment by vweevers** [comment]
No, because [lockfiles are for apps](https://github.com/sindresorhus/ama/issues/479#issuecomment-310661514).

**Comment by feross** [comment]
Yep, I agree with @vweevers. The lockfile only applies when running `npm install` directly in the airtap folder (i.e. a local install). It's never published to npm, so it won't affect what users get.

Committing it would only make developers of airtap (us) get a different (older) set of dependencies than users would get at install time.
