### ISSUE TITLE
Default to not running sauce labs tests on Travis/CI?

### ISSUE THREAD

**Issue by feross** [airtap/airtap#66]
Travis doesn't make encrypted environment variables available when receiving PRs from external contributors. This is a security feature to prevent a random user from making a PR that prints out the environment variables and stealing them.

The problem is that this default behavior means that any test suite that includes `airtap` automatically fails on every PR from external contributors. So you have to write a custom test script that detects Travis PRs and doesn't run `airtap`. For example:

```
var shouldRunBrowserTests = !process.env.TRAVIS_PULL_REQUEST ||
  process.env.TRAVIS_PULL_REQUEST === 'false'
```

Could airtap be opinionated and handle this common case? Specifically, when running on CI and the Sauce Labs env variables are missing (which happens on PRs), default to just skipping the tests and exiting cleanly?

Or how about a flag to do that? `--skip-missing-credentials` or `--skip-pr`

**Comment by vweevers** [comment]
Agree that we should handle this.

How about skipping tests if `process.env.TRAVIS_SECURE_ENV_VARS !== 'true'`?

From https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables:

> TRAVIS_SECURE_ENV_VARS:
>-  set to true if there are any encrypted environment variables.
> - set to false if no encrypted environment variables are available.

**Comment by feross** [comment]
Sounds good to me! Let's make sure to print a message so the user knows what's happening if they read the logs.

Note, I don't think you want to skip tests if `process.env.TRAVIS_SECURE_ENV_VARS` is `undefined` which will happen when e.g. running locally, so how about this test:

```
var shouldSkip = process.env.TRAVIS_SECURE_ENV_VARS === 'false'
```

**Comment by vweevers** [comment]
> Sounds good to me! Let's make sure to print a message so the user knows what's happening if they read the logs.

👍 

> Note, I don't think you want to skip tests if process.env.TRAVIS_SECURE_ENV_VARS is undefined

Ah right. SGTM.

**Comment by ralphtheninja** [comment]
So we shouldn't run `test/integration/tape-sauce.js` on PRs but the rest of the tests should be fine? We need to make a seam somewhere then so we can split up the tests. Maybe just in `test/index.js`, e.g.:

```js
require('./unit/aggregate-browsers')
require('./unit/browserify-builder')
require('./unit/capabilities')
require('./unit/flatten-browser')
require('./integration/tape-electron')
require('./integration/tape-phantom')

if (process.env.TRAVIS_SECURE_ENV_VARS !== 'false') {
  require('./integration/tape-sauce')
}
```

**Comment by ralphtheninja** [comment]
@feross Let me know if you're happy with this and I'll get it done.

**Comment by ralphtheninja** [comment]
After this maybe release `0.0.4`?

**Comment by feross** [comment]
@ralphtheninja This issue is about adding a feature that will allow *users* of airtap to skip running tests entirely on PRs, since those lack credentials.

So, I could add airtap to a project like `buffer` without needing to write code to detect if we're in a Travis PR. We want to skip airtap in PRs, because the credentials are missing. See this line: https://github.com/feross/buffer/blob/c0c91b75e43d5ef82c246e4d8f3746b5e779aded/bin/test.js#L7-L8

If we need the same thing for our own tests, it would be nice to just implement this for everyone, either via a `--skip-missing-credentials` or `--skip-pr` flag, or just defaulting to this behavior if that's what folks think makes the most sense. Then we can just use the flag in our own airtap test suite :)

**Comment by ralphtheninja** [comment]
> @ralphtheninja This issue is about adding a feature that will allow users of airtap to skip running tests entirely on PRs, since those lack credentials.

Oh right. Gotcha!

**Comment by feross** [comment]
Yes, I think so.
