### ISSUE TITLE
Use `husky` with `lint-staged` as a precommit hook

### ISSUE THREAD

**Issue by yeskunall** [airtap/airtap#68]
It'll help ensure that the files are linted before being pushed to remote (or any other branch, for that matter!)

I have not had the pleasure of using StandardJS yet in any of my projects, but I'm sure this can be done. 😅

#### Motivation
To avoid commits like 4b60f02ec4d4da5c31b2fbb8fc9dfdabc72431e3. 😬

/cc @feross

**Comment by feross** [comment]
I have no opinion on this – I just always run `npm test` before pushing

**Comment by yeskunall** [comment]
Hmm 🤔 maybe just run the `lint` script as a precommit hook, then?

BTW, thanks for the quick response. 😁

**Comment by vweevers** [comment]
Adds complexity for little gain, I think.

> To avoid commits like 4b60f02.

That's why I squashed it (https://github.com/airtap/airtap/commit/be5a2c23cf90b0611ffb72c9795c6c23ff7fabbb). Problem gone ;)

**Comment by yeskunall** [comment]
Agreed, you guys. Closing. 🤗
