### ISSUE TITLE
Remove PhantomJS

### ISSUE THREAD

**Issue by vweevers** [airtap/airtap#7]
Thumbs up?

**Comment by mcollina** [comment]
Definitely for me.

**Comment by ralphtheninja** [comment]
I changed my mind. I think it's kind of nice to use phantomjs locally when testing things.

**Comment by vweevers** [comment]
I think we can keep support for PhantomJS if we decouple it like you proposed in #47.

**Comment by feross** [comment]
I think we should remove it. The project is now dead, according to the maintainer: https://github.com/ariya/phantomjs/issues/15344

I'm not against a plugin for it, but I don't think anyone ought to use it anymore.

**Comment by ralphtheninja** [comment]
Lets get rid of it then :fire:

**Comment by ralphtheninja** [comment]
Also means we can upgrade `tap-parser` which had some issues with PhantomJS iirc.
