### ISSUE TITLE
Add list of projects using airtap to README?

### ISSUE THREAD

**Issue by ralphtheninja** [airtap/airtap#70]
[![](https://api.gh-polls.com/poll/01C6X0TG3M71CH47J73617MM7K/Yes)](https://api.gh-polls.com/poll/01C6X0TG3M71CH47J73617MM7K/Yes/vote)
[![](https://api.gh-polls.com/poll/01C6X0TG3M71CH47J73617MM7K/No)](https://api.gh-polls.com/poll/01C6X0TG3M71CH47J73617MM7K/No/vote)

**Comment by feross** [comment]
Nice, seems like there is consensus. Sent a PR: https://github.com/airtap/airtap/pull/74
