### ISSUE TITLE
a little confusion about https://github.com/airtap/airtap#install

### ISSUE THREAD

**Issue by chinanf-boy** [airtap/airtap#78]
in Install, show
```
npm install airtap --save-dev
```

---

in Next, example

```
airtap --local 8080 test.js
```

and i run the `cmd` before, i jump to [zuul-wiki-installation](https://github.com/defunctzombie/zuul/wiki/installation) { before i don't know zuul } and `See`
`npm install -g zuul`, then i try `npm install -g airtap`

Yes, `airtap` is download global success , but i think that cmd like `npm install -g airtap` should be have a seat in [airtap/README.md](https://github.com/airtap/airtap/blob/master/README.md)

😊can it?❤️

**Comment by ralphtheninja** [comment]
Yes, we should maybe write something like `npm install airtap --save-dev | -g` or similar. It depends on if you want it as a devDependency or installed globally.
