### ISSUE TITLE
Fix the rest of standard

### ISSUE THREAD

**Issue by ralphtheninja** [airtap/airtap#87]
Prerequisite:

- [x] merge `cleanup-frameworks`
- [x] merge `remove-ui-option`
- [x] merge `remove-mocha`
- [x] merge `update-doc`

Files:

- [x] `bin/airtap.js`
- [ ] `frameworks/render-stacktrace.js`
- [ ] `frameworks/tape.js`
- [ ] `frameworks/zuul.js`
- [ ] `lib/SauceBrowser.js`
- [ ] `lib/airtap.js`
- [ ] `lib/builder-browserify.js`
- [ ] `lib/control-app.js`
- [ ] `lib/flatten-browserlist.js`
- [ ] `lib/get-saucelabs-browsers.js`
- [ ] `lib/setup.js` (@yeskunall)
- [ ] `lib/user-server.js`
- [ ] `test/auth.js` (@ralphtheninja)
- [ ] `test/integration/tape-sauce.js` (@ralphtheninja)
- [ ] `test/unit/browserify-builder.js` (@ralphtheninja)
- [ ] `test/unit/capabilities.js` (@ralphtheninja)

And:

- [ ] investigate if all fixtures are being used (currently ignored by `standard`), if that's the case then they should also be fixed, otherwise removed
- [ ] clean up ignore patterns from `package.json`
- [ ] make `standard` actually error

Some files are hairier than others and we might need to do this in multiple PRs, YMMV.

**Comment by ralphtheninja** [comment]
I think I want to finish this one off once and for all, so we can continue on other stuff. It's sort of in the way right now and the errors are really spamming the test logs.

**Comment by yeskunall** [comment]
Just in case other people want to work on this: I suggest people comment here saying which task(s) they want to take up, and submit an individual PR for each of the tasks. It'll be easier that way, IMO. 😅

**Comment by ralphtheninja** [comment]
@yeskunall Ok. I'm gonna start with the `test/` folder.

**Comment by vweevers** [comment]
In case standard doesn't warn about this, let's add a semicolon before this IIFE (or don't use an IIFE):

https://github.com/airtap/airtap/blob/b643d9ae81e69719bb693dfa9477dcb152391d93/lib/sauce-browser.js#L178

**Comment by ralphtheninja** [comment]
@vweevers `standard` does warn about it and I used a semicolon :smile:

**Comment by ralphtheninja** [comment]
What's an IIFE btw?

**Comment by ralphtheninja** [comment]
Oh wait, that's another place in the code. Not sure standard warns about it. My bad.

**Comment by vweevers** [comment]
Immediately invoked function expression. E.g. `(function foo(){})()`. I don't like them much, find `function foo() {}; foo()` easier to read.

**Comment by ralphtheninja** [comment]
Create an issue on that. We should rewrite them.

**Comment by vweevers** [comment]
#104
