### ISSUE TITLE
Remove frameworks other than tap(e)

### ISSUE THREAD

**Issue by vweevers** [airtap/airtap#9]
Thumbs up?

**Comment by mcollina** [comment]
:+1:

**Comment by vweevers** [comment]
I'll start looking into this, see what we need to do.

**Comment by vweevers** [comment]
- [ ] Remove `ui` option from `test/integration/capabilities.js` (so that it defaults to tape)
- [ ] Remove `test/integration/jamine-phantom.js` (no added value, not worth rewriting as tape test)
- [ ] Rewrite `test/integration/mocha-qunit-sauce.js` and `fixtures/mocha-qunit` to use tape
- [ ] Remove `test/integration/mocha-qunit-phantom.js` (uses same fixture as `mocha-qunit-sauce` test)
- [ ] Remove `test/integration/mochabdd-phantom.js` (no added value)
- [ ] Remove `ui` option from `bin/airtap`
- [ ] Remove references to emberjs example in `doc/airtap.yml.md`
- [ ] Change example in `doc/travis-matrix.md` to use tape instead of mocha
- [ ] Remove exports from `frameworks/index.js`
- [ ] Remove `frameworks/*` except for tape
- [ ] Flatten the `frameworks/tape` directory or move it to `lib`
- [ ] Remove devDependencies (and `dependency-check -i`): mocha, qunit

**Comment by ralphtheninja** [comment]
Also

- [ ] Remove `frameworks/tape/framework.js`
- [ ] Remove `<script src="/__zuul/framework.js"></script>` from `frameworks/index.html`

**Comment by ralphtheninja** [comment]
I'd like to take this on if no one has any objections.

**Comment by ralphtheninja** [comment]
@vweevers Correct me if I'm wrong, but it seems to me the end result would be

* only _one_ fixture, e.g. `test/fixtures/tape/test.js` 
* two integration tests for browsers, `test/integrations/tape-phantom.js` and `test/integrations/tape-sauce.js`

**Comment by vweevers** [comment]
Right. It's not much.
