### ISSUE TITLE
Tweak frameworks and lib folder structure

### ISSUE THREAD

**Issue by ralphtheninja** [airtap/airtap#94]
Maybe

* `frameworks/` -> `client/` or `web/`?
* `lib/` -> `server/`?

**Comment by ralphtheninja** [comment]
Would make it more clear what is running server side and client side respectively.

**Comment by vweevers** [comment]
+1 to `client/`

No opinion on `server/`. I think `lib/` is also fine and when we have `client/` the distinction is already clear.
