### ISSUE TITLE
Double initialization of self.stats in SauceBrowser.js

### ISSUE THREAD

**Issue by ralphtheninja** [airtap/airtap#95]
https://github.com/airtap/airtap/blob/54d99c2cc32174f832548ab208586b247d6071b5/lib/SauceBrowser.js#L18-L21

and

https://github.com/airtap/airtap/blob/54d99c2cc32174f832548ab208586b247d6071b5/lib/SauceBrowser.js#L39-L42

~~Remove the one in the constructor.~~ Remove the one in `.start()`.

**Comment by vweevers** [comment]
> Remove the one in the constructor.

Would do it the other way around. Define properties early, in the constructor. That has a perf benefit (less hidden classes), though that doesn't matter here, so more importantly, it communicates to developers what the properties of `SauceBrowser` are.

**Comment by vweevers** [comment]
Related: the property is called `status` in PhantomBrowser and Electron:

https://github.com/airtap/airtap/blob/3360313d135466b4e3db828d4097e1f578c35930/lib/Electron.js#L17-L20

We should rename that to `stats`, so that later, all three can inherit from an `AbstractBrowser`, and then we can define `stats` there.

**Comment by vweevers** [comment]
@ralphtheninja I found out it's not a double initialization, but a reset. Due to retries, `start` can be called multiple times, and so, it needs to reset `stats`.

**Comment by ralphtheninja** [comment]
> @ralphtheninja I found out it's not a double initialization, but a reset. Due to retries, start can be called multiple times, and so, it needs to reset stats.

So we can remove it from the constructor :wink:

**Comment by vweevers** [comment]
I took a different route, with a `resetStats` method on `AbstractBrowser`. PR coming in a bit.
