### ISSUE TITLE
Run unit tests before integration tests

### ISSUE THREAD

**Issue by ralphtheninja** [airtap/airtap#98]
Even if integration tests might fail locally we should at least run the unit tests before they fail.

**Comment by vweevers** [comment]
Good idea :) also helpful in CI builds

**Comment by vweevers** [comment]
@ralphtheninja I added an electron test (and fixed electron), so I'll rebase that once you're done.

**Comment by vweevers** [comment]
@ralphtheninja on second thought.. I assume you just mean to change the order of:

https://github.com/airtap/airtap/blob/6202fcf6e7a81ce38676691087bcfd4b5b7fa575/test/index.js#L1-L6

If so, I'll take that on if you don't mind.

**Comment by ralphtheninja** [comment]
> @ralphtheninja on second thought.. I assume you just mean to change the order of:

Exactly!

**Comment by ralphtheninja** [comment]
@vweevers Also, can you make it so `tape-phantom` runs before `tape-sauce`?

**Comment by vweevers** [comment]
Yup did that :)
